# Final Project
## Spring 2026
## DATA 3421
### Noe Martinez, Tanvir Signh, Aaron White

In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [26]:
pd.set_option('display.max_columns', 100)

FILEPATH = 'heart_attack_prediction_dataset.csv'
df = pd.read_csv(FILEPATH)

In [ ]:
col_name_map = {col: col.replace(' ', '_') for col in df.columns}
df = df.rename(columns=col_name_map)

In [33]:
df.shape

(8763, 26)

In [34]:
# No duplicate records
df.loc[df.duplicated()]

Empty DataFrame
Columns: [Patient_ID, Age, Sex, Cholesterol, Blood_Pressure, Heart_Rate, Diabetes, Family_History, Smoking, Obesity, Alcohol_Consumption, Exercise_Hours_Per_Week, Diet, Previous_Heart_Problems, Medication_Use, Stress_Level, Sedentary_Hours_Per_Day, Income, BMI, Triglycerides, Physical_Activity_Days_Per_Week, Sleep_Hours_Per_Day, Country, Continent, Hemisphere, Heart_Attack_Risk]
Index: []

In [35]:
df

,Patient_ID,Age,Sex,Cholesterol,Blood_Pressure,Heart_Rate,Diabetes,Family_History,Smoking,Obesity,Alcohol_Consumption,Exercise_Hours_Per_Week,Diet,Previous_Heart_Problems,Medication_Use,Stress_Level,Sedentary_Hours_Per_Day,Income,BMI,Triglycerides,Physical_Activity_Days_Per_Week,Sleep_Hours_Per_Day,Country,Continent,Hemisphere,Heart_Attack_Risk
0,BMW7812,67,Male,208,158/88,72,0,0,1,0,0,4.168189,Average,0,0,9,6.615001,261404,31.251233,286,0,6,Argentina,South America,Southern Hemisphere,0
1,CZE1114,21,Male,389,165/93,98,1,1,1,1,1,1.813242,Unhealthy,1,0,1,4.963459,285768,27.194973,235,1,7,Canada,North America,Northern Hemisphere,0
2,BNI9906,21,Female,324,174/99,72,1,0,0,0,0,2.078353,Healthy,1,1,9,9.463426,235282,28.176571,587,4,4,France,Europe,Northern Hemisphere,0
3,JLN3497,84,Male,383,163/100,73,1,1,1,0,1,9.828130,Average,1,0,9,7.648981,125640,36.464704,378,3,4,Canada,North America,Northern Hemisphere,0
4,GFO8847,66,Male,318,91/88,93,1,1,1,1,0,5.804299,Unhealthy,1,0,6,1.514821,160555,21.809144,231,1,5,Thailand,Asia,Northern Hemisphere,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8758,MSV9918,60,Male,121,94/76,61,1,1,1,0,1,7.917342,Healthy,1,1,8,10.806373,235420,19.655895,67,7,7,Thailand,Asia,Northern Hemisphere,0
8759,QSV6764,28,Female,120,157/102,73,1,0,0,1,0,16.558426,Healthy,0,0,8,3.833038,217881,23.993866,617,4,9,Canada,North America,Northern Hemisphere,0
8760,XKA5925,47,Male,250,161/75,105,0,1,1,1,1,3.148438,Average,1,0,5,2.375214,36998,35.406146,527,4,4,Brazil,South America,Southern Hemisphere,1
8761,EPE6801,36,Male,178,119/67,60,1,0,1,0,0,3.789950,Unhealthy,1,1,5,0.029104,209943,27.294020,114,2,8,Brazil,South America,Southern Hemisphere,0
8762,ZWN9666,25,Female,356,138/67,75,1,1,0,0,1,18.081748,Healthy,0,0,8,9.005234,247338,32.914151,180,7,4,United Kingdom,Europe,Northern Hemisphere,1